### ISSUE TITLE
Remove template cruft

### ISSUE THREAD

**Issue by ForbesLindesay** [jstransformers/jstransformer-css#1]
Could you remove everything that was added by your automated templates please?
- .coveralls.yml
- .editorconfig
- .gitattributes
- .jscsrc
- .jshintignore
- .jshintrc
- extra scripts for linting in package.json
- Comment header on js file
- Author section of readme 

Could you then put tests and expected output/sample input in a separate folder as is done on other projects and update capitalisation of LICENSE file etc.

Please use other libraries in this org as a guide and do not create using automated scripts that are normally used for personal projects.

**Comment by tunnckoCore** [comment]
coveralls, right, okey. but other dotfiles why?

sorry for the delay, Im curios why github not notify me about this issues, lol

**Comment by tunnckoCore** [comment]
> Could you then put tests and expected output/sample input in a separate folder as is done on other projects

yea, see my latest libs in org :)

**Comment by ForbesLindesay** [comment]
Having three linters for about 50 lines of JavaScript is madness.  The more files there are, the harder it is for new people to find the files that actually matter.  Fewer files -> easier to contribute to.

**Comment by tunnckoCore** [comment]
lol, yea maybe its madness, but I think we dont need people who dont know that in nodejs land entry point is index.js in 99% of the time or lib/index.js in other 1%. Except that.. all of us know that dotfiles are basically nothing more than code style / lint / CI.

**Comment by tunnckoCore** [comment]
will normalize it tomorrow

**Comment by ForbesLindesay** [comment]
There are many front end developers with no experience of node.js.  It would be great if some people could have jstransformers as their first experience contributing to open source.  Hopefully we can make that experience really great for them so they keep coming back.
