### ISSUE TITLE
Test It package

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-css#2]
Probably don't need testit since it's just four simple assertions and only two tests :wink: .

**Comment by tunnckoCore** [comment]
@jstransformers/owners 
Okey why you do this? Why is this strictness, guys? Let everyone work as he want and follow simple code and visual style, nothing more, nothing less. Let discuss these things first and end with some points, then we'll normalize all the repos and things.

**Comment by RobLoach** [comment]
Oh, I see it in the Boilerplate :-) .... Thank! :+1:

**Comment by tunnckoCore** [comment]
Not only this.

**Comment by ForbesLindesay** [comment]
This, in particular, I don't think matters either way.  If you think it would be better without, submit a pull request, if not, leave it be.

In general, we are being really strict about a lot of things at this stage to make sure that all transformers are consistent and of the same high quality.  This is both to give users a high degree of trust in jstransformers and to make it as easy as possible for people to contribute.
